service: timeout-api

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221

  stage: dev
  region: eu-west-1

  iamRoleStatements:
  - Effect: Allow
    Action:
      - lambda:InvokeFunction
    Resource: arn:aws:lambda:*:*:function:*
  - Effect: Allow
    Action:
      - sqs:DeleteMessage
      - sqs:ReceiveMessage
    Resource: arn:aws:sqs:*:*:${self:custom.timeoutTransactions}
    - Effect: Allow
      Action:
        - s3:GetItem
        - s3:PutItem
        - s3:GetObject
        - s3:PutObject
        - s3:ListObject
        - s3:Get*
        - s3:Put*
      Resource: arn:aws:s3:::${self:custom.verificationItemsBucket}
    - Effect: Allow
      Action:
        - s3:GetItem
        - s3:PutItem
        - s3:GetObject
        - s3:PutObject
        - s3:ListObject
        - s3:Get*
        - s3:Put*
      Resource: arn:aws:s3:::${self:custom.verificationItemsBucket}/*

package:
  patterns:
    - '!./**'
    - ./bin/**

custom:
  region: ${self:provider.region}
  prefix: ${self:provider.stage}-${self:service}
  timeoutTransactions: ${self:custom.prefix}-timeout-transactions
  verificationItemsBucket: ${self:custom.prefix}-timeout-transactions-verification-items

functions:
  # transaction-api:
  #   handler: bin/verification-api
  #   description: Verify transactions from API and DynamoDb object query.
  #   events:
  #     - httpApi:
  #         path: /verifyTransaction
  #         method: get
  #   environment:
  #     latencyTable: ${self:custom.latencyTable}
  verification-api:
    handler: bin/verification-api
    description: Get verification api events from CSV
    events:
      - s3: ${self:custom.verificationItemsBucket}
    environment:
      verificationItemsBucket: ${self:custom.verificationItemsBucket}
      region: ${self:custom.region}

resources:
  Resources:
    Transactions:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.timeoutTransactions}
        MessageRetentionPeriod: 1209600
        VisibilityTimeout: 60
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
            - MessagesDeadLetterQueue
            - Arn
          maxReceiveCount: 10

    MessagesDeadLetterQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.timeoutTransactions}-dead-letter-queue
        MessageRetentionPeriod: 1209600
